In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine, text

schema = "tester_lib"
host = "127.0.0.1"
user = "root"
password = os.getenv("MYSQL_PASSWORD")
port = 3306

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

engine = create_engine(connection_string)

In [4]:
def read_friends():
    return pd.read_sql('friends', con=engine)

# Core CRUD Workflow

**Workflows covered:**
1. Setup & Engine Connection
2. Read `friends` & `books` tables (+ test after each)
3. Create a friend & loan using dynamically selected row data (+ test)
4. Update a friend using dynamic selection (+ test)
5. Delete a friend using dynamic selection (+ test)

## 0. Setup & Engine Connection

In [5]:
import os
import pandas as pd
from sqlalchemy import create_engine, text

schema = "tester_lib"
host = "127.0.0.1"
user = "root"
password = os.getenv("MYSQL_PASSWORD")
port = 3306

connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}"
engine = create_engine(connection_string)

In [6]:
read_friends()

   friend_id       name  max_loans notes
0          1  christine          5   NaN
1          2  christine          5   NaN
2          3  christine          5   NaN
3          4  christine          5   NaN
4          5      Marie          3   NaN
5          6      Marie          3   NaN

In [7]:
def read_books(available_only=False):
    books = pd.read_sql("books", con=engine)
    loans= pd.read_sql("loans", con=engine)

    if available_only == True:
        books = pd.merge(books, loans, on='isbn', how='left').query('friend_id.isna()')[books.columns]

    return books

In [8]:
read_books(available_only=True)

,title,author,genre,isbn
1,Sapiens: A Brief History of Humankind,Yuval Noah Harari,Nonfiction,9780143127741
2,The Wind-Up Bird Chronicle,Haruki Murakami,Fiction,9780307949486
3,The Poisonwood Bible,Barbara Kingsolver,Fiction,9780385490818
4,"Thinking, Fast and Slow",Daniel Kahneman,Psychology,9780553386790
5,Echoes of the Past,Julian Marsh,Thriller,9780987654321
6,The Secret Ingredient,Samira Nouri,Romance,9781122334455
7,The Paper Trail,Liane Forestier,Historical Fiction,9781234567890
8,The Clockmaker's Son,Hugo Vernier,Steampunk,9784455667788
9,Gardens of Glass,Ivy Thornton,Fantasy,9785566778899

In [9]:
read_books()

,title,author,genre,isbn
0,The Alchemist,Paulo Coelho,Fiction,9780062316110
1,Sapiens: A Brief History of Humankind,Yuval Noah Harari,Nonfiction,9780143127741
2,The Wind-Up Bird Chronicle,Haruki Murakami,Fiction,9780307949486
3,The Poisonwood Bible,Barbara Kingsolver,Fiction,9780385490818
4,"Thinking, Fast and Slow",Daniel Kahneman,Psychology,9780553386790
5,Echoes of the Past,Julian Marsh,Thriller,9780987654321
6,The Secret Ingredient,Samira Nouri,Romance,9781122334455
7,The Paper Trail,Liane Forestier,Historical Fiction,9781234567890
8,The Clockmaker's Son,Hugo Vernier,Steampunk,9784455667788
9,Gardens of Glass,Ivy Thornton,Fantasy,9785566778899

In [10]:
books = pd.read_sql("books", con=engine)
loans= pd.read_sql("loans", con=engine)

available_books = pd.merge(books, loans, on='isbn', how='left').query('friend_id.isna()')

available_books

,title,author,genre,isbn,friend_id,loan_date,last_contact,next_contact,notes
1,Sapiens: A Brief History of Humankind,Yuval Noah Harari,Nonfiction,9780143127741,NaN,NaT,NaT,NaT,NaN
2,The Wind-Up Bird Chronicle,Haruki Murakami,Fiction,9780307949486,NaN,NaT,NaT,NaT,NaN
3,The Poisonwood Bible,Barbara Kingsolver,Fiction,9780385490818,NaN,NaT,NaT,NaT,NaN
4,"Thinking, Fast and Slow",Daniel Kahneman,Psychology,9780553386790,NaN,NaT,NaT,NaT,NaN
5,Echoes of the Past,Julian Marsh,Thriller,9780987654321,NaN,NaT,NaT,NaT,NaN
6,The Secret Ingredient,Samira Nouri,Romance,9781122334455,NaN,NaT,NaT,NaT,NaN
7,The Paper Trail,Liane Forestier,Historical Fiction,9781234567890,NaN,NaT,NaT,NaT,NaN
8,The Clockmaker's Son,Hugo Vernier,Steampunk,9784455667788,NaN,NaT,NaT,NaT,NaN
9,Gardens of Glass,Ivy Thornton,Fantasy,9785566778899,NaN,NaT,NaT,NaT,NaN

In [11]:
read_books()

,title,author,genre,isbn
0,The Alchemist,Paulo Coelho,Fiction,9780062316110
1,Sapiens: A Brief History of Humankind,Yuval Noah Harari,Nonfiction,9780143127741
2,The Wind-Up Bird Chronicle,Haruki Murakami,Fiction,9780307949486
3,The Poisonwood Bible,Barbara Kingsolver,Fiction,9780385490818
4,"Thinking, Fast and Slow",Daniel Kahneman,Psychology,9780553386790
5,Echoes of the Past,Julian Marsh,Thriller,9780987654321
6,The Secret Ingredient,Samira Nouri,Romance,9781122334455
7,The Paper Trail,Liane Forestier,Historical Fiction,9781234567890
8,The Clockmaker's Son,Hugo Vernier,Steampunk,9784455667788
9,Gardens of Glass,Ivy Thornton,Fantasy,9785566778899

In [12]:
def read_loans():
    return pd.read_sql("loans", con=engine)

In [13]:
read_loans()

,isbn,friend_id,loan_date,last_contact,next_contact,notes
0,9780062316110,1,2024-06-01,NaT,2024-06-15,Handle with care

## 2. Create friend/Loan

add marie in with python with sql query

In [14]:
engine = create_engine(connection_string)

update_query = """
insert into friends (`name`, max_loans) values ('Marie', 3);
"""

with engine.connect() as connection :
    transaction = connection.begin()
    try:
        connection.execute(text(update_query))
        transaction.commit()
    except:
        transaction.rollback()
        raise

In [15]:
read_friends()

   friend_id       name  max_loans notes
0          1  christine          5   NaN
1          2  christine          5   NaN
2          3  christine          5   NaN
3          4  christine          5   NaN
4          5      Marie          3   NaN
5          6      Marie          3   NaN
6          7      Marie          3   NaN

and make into function

In [16]:
def create_friend(name,max_loans=5,notes=None):
    df = pd.DataFrame([[name,max_loans,notes]], columns=['name','max_loans','notes'])
    df.to_sql('friends', if_exists='append', con=engine, index=False) #index if you dont want to keep panda index
    return f"{name} is added to the list"

In [17]:
create_friend("christine")

'christine is added to the list'

books, friends
friend_name, isbn, loan_date, next contact, notes

In [18]:
#boolean mask 
friends_df = read_friends() 
friend_name = "christine"
# find the friend_id from friends table 
friend = friends_df [friends_df['name'] == friend_name].iloc[0]

In [25]:
# create a loan
def create_loan(friend_name, isbn, loan_date=None, next_contact=None, notes=None):
    friends_df = read_friends()
    books_df = read_books()
    loans_df = read_loans()

    friend_rows = friends_df[friends_df["name"] == friend_name]
    book_rows = books_df[books_df["isbn"] == isbn]

    if friend_rows.empty:
        raise ValueError(f"Friend not found: {friend_name}")
    if book_rows.empty:
        raise ValueError(f"Book not found: {isbn}")

    friend_id = int(friend_rows.iloc[0]["friend_id"])
    if not loans_df[(loans_df["isbn"] == isbn) & (loans_df["friend_id"] == friend_id)].empty:
        return f"Loan already exists for {friend_name} and {isbn}"

    loan = pd.DataFrame(
        [[isbn, friend_id, loan_date, next_contact, notes]],
        columns=["isbn", "friend_id", "loan_date", "next_contact", "notes"]
    )
    loan.to_sql("loans", con=engine, if_exists="append", index=False)

    return f"{friend_name} has borrowed {book_rows.iloc[0]['title']}"

lets test

In [26]:
create_loan("christine","9780062316110", loan_date="2024-06-01", next_contact="2024-06-15", notes="Handle with care")

'Loan already exists for christine and 9780062316110'

## 3. Update Friend

## 4. Delete Friend